# -------------- **Numpy Basic** --------------

                             "26 January 2024"   - Akanksha              

NumPy, short for Numerical Python, is a powerful library in Python for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays. NumPy is a fundamental package for scientific computing in Python and is widely used in fields such as machine learning, data science, and engineering. Let's delve into the basics of NumPy:

### 1. **Installation:**
   You can install NumPy using `pip`:



In [13]:
 pip install numpy

### 2. **Importing NumPy:**
   After installation, you can import NumPy into your Python script or Jupyter notebook:



   It's a common convention to alias NumPy as `np`.



In [14]:
   import numpy as np

### 3. **NumPy Arrays:**
   The primary data structure in NumPy is the array. An array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. There are several ways to create NumPy arrays:

   - **Using Lists:**
     ```python
     arr = np.array([1, 2, 3, 4, 5])
     ```

   - **Using arange():**
     ```python
     arr = np.arange(0, 10, 2)  # Creates an array from 0 to 10 with a step of 2
     ```

   - **Using linspace():**
     ```python
     arr = np.linspace(0, 1, 5)  # Creates an array of 5 evenly spaced values between 0 and 1
     ```

   - **Zeros and Ones:**
     ```python
     zeros_arr = np.zeros((3, 3))  # Creates a 3x3 array of zeros
     ones_arr = np.ones((2, 4))    # Creates a 2x4 array of ones
     ```



In [16]:
arr = np.array([1, 2, 3, 4, 5])

### 4. **Array Attributes:**
   - **Shape:**
     ```python
     shape = arr.shape  # Returns the dimensions of the array
     ```

   - **Dtype:**
     ```python
     dtype = arr.dtype  # Returns the data type of the array
     ```

   - **Size:**
     ```python
     size = arr.size  # Returns the total number of elements in the array
     ```



In [19]:
shape = arr.shape
dtype = arr.dtype
size = arr.size

print('Shape of the array =',shape)
print('Data Type of the array =',dtype)
print('Size of the array =',size)

Shape of the array = (5,)
Data Type of the array = int64
Size of the array = 5


### 5. **Indexing and Slicing:**
   - NumPy arrays use zero-based indexing.
   - Slicing works similarly to Python lists.




In [15]:
   arr = np.array([0, 1, 2, 3, 4, 5])
   print(arr[2])      # Access element at index 2
   print(arr[1:4])    # Slice elements from index 1 to 3

2
[1 2 3]


### 6. **Array Operations:**
   - NumPy allows for element-wise operations on arrays.





In [24]:
   arr1 = np.array([1, 2, 3])
   arr2 = np.array([4, 5, 6])

   sum_arr = arr1 + arr2       # Element-wise addition
   product_arr = arr1 * arr2   # Element-wise multiplication

### 7. **Mathematical Functions:**
   NumPy provides a plethora of mathematical functions that operate on arrays:





In [23]:
   sin_arr = np.sin(arr)
   cos_arr = np.cos(arr)
   exp_arr = np.exp(arr)

   print('Sin of the array =', sin_arr)
   print('cos of the array =', cos_arr)
   print('Exponential of the array =', exp_arr)

Sin of the array = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos of the array = [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Exponential of the array = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### 8. **Linear Algebra:**
   NumPy has a `linalg` module for linear algebra operations:





In [27]:
   A = np.array([[1, 2], [3, 4]])
   det_A = np.linalg.det(A)       # Determinant of A
   inv_A = np.linalg.inv(A)       # Inverse of A

   print('Determinant of the array =', det_A)
   print('Inverse of the array =', inv_A)

Determinant of the array = -2.0000000000000004
Inverse of the array = [[-2.   1. ]
 [ 1.5 -0.5]]


### 9. **Random Module:**
   NumPy provides a `random` module for generating random numbers:





In [29]:
rand_arr = np.random.rand(3, 3)  # 3x3 array of random values between 0 and 1

print('Random of the array =', rand_arr)

Random of the array = [[0.14122882 0.96783548 0.76897065]
 [0.96443515 0.09179714 0.30007155]
 [0.66342406 0.50842179 0.94089468]]


### 10. **Broadcasting:**
   NumPy allows for broadcasting, a powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations.


In [32]:
arr = np.array([1, 2, 3])
scalar_multiply = arr * 2  # Broadcasting the scalar to each element

print ('Array = ', scalar_multiply)

Array =  [2 4 6]
