# -------------- **Numpy Random** --------------

                             "27 January 2024"   - Akanksha              

NumPy is a powerful numerical computing library in Python, and it provides a module called `numpy.random` for generating random numbers. The `numpy.random` module is widely used in various scientific and statistical applications, as well as in simulations and machine learning.

Here's a detailed overview of the key functions and features within the `numpy.random` module:

## 1. **Simple Random Data Generation:**

### 1.1 `numpy.random.rand`
- Generates random values from a uniform distribution over `[0, 1)`.




In [2]:
import numpy as np
random_values = np.random.rand(3, 3)
print(random_values)

[[0.30278154 0.24244149 0.87154427]
 [0.42187336 0.19408982 0.47314756]
 [0.31894145 0.84264367 0.66112366]]


### 1.2 `numpy.random.randn`
- Returns samples from the standard normal distribution (mean=0, variance=1).




In [3]:
import numpy as np
random_samples = np.random.randn(3, 3)
print(random_samples)

[[-0.06023423 -0.24190116  0.64424639]
 [-0.46512494  0.66736547  2.08895943]
 [ 0.99285796 -1.10062584 -1.08541745]]


### 1.3 `numpy.random.randint`
- Generates random integers from a specified low (inclusive) to high (exclusive) range.




In [4]:
import numpy as np
random_integers = np.random.randint(1, 10, size=(3, 3))
print(random_integers)

[[1 2 4]
 [3 6 4]
 [1 8 8]]


## 2. **Permutations:**

### 2.1 `numpy.random.shuffle`
- Shuffles the elements of an array in-place.



In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[3 4 5 2 1]


### 2.2 `numpy.random.permutation`
- Randomly permutes a sequence or returns a permuted range.




In [8]:
import numpy as np
arr = np.random.permutation(10)
print(arr)

[9 7 2 5 0 1 8 6 3 4]


## 3. **Distributions:**

### 3.1 `numpy.random.normal`
- Generates random samples from a normal (Gaussian) distribution.




In [9]:
import numpy as np
normal_samples = np.random.normal(loc=0, scale=1, size=(3, 3))
print(normal_samples)

[[ 1.30696015  0.21362734 -1.35965082]
 [-1.14044621  0.38934098  1.33448286]
 [ 0.38757241 -0.25103805  0.98203332]]


### 3.2 `numpy.random.uniform`
- Draws samples from a uniform distribution.




In [10]:
import numpy as np
uniform_samples = np.random.uniform(low=0, high=1, size=(3, 3))
print(uniform_samples)

[[0.50099568 0.21748744 0.27874655]
 [0.73438748 0.97482337 0.14514303]
 [0.06755578 0.97056914 0.53425842]]


### 3.3 `numpy.random.exponential`
- Generates samples from an exponential distribution.




In [11]:
import numpy as np
exponential_samples = np.random.exponential(scale=1, size=(3, 3))
print(exponential_samples)

[[0.27369379 0.75295203 1.23128179]
 [2.71149417 1.48109833 0.57581196]
 [0.0062058  1.93640866 0.10289211]]


## 4. **Random Generator:**

### 4.1 `numpy.random.RandomState`
- Creates a random number generator with a specified seed.





In [13]:
import numpy as np
rng = np.random.RandomState(seed=42)
random_values = rng.rand(3, 3)
print(random_values)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


## 5. **Seed Control:**

### 5.1 `numpy.random.seed`
- Seed the generator to produce reproducible results.




In [14]:
import numpy as np
np.random.seed(42)
random_values = np.random.rand(3, 3)
print(random_values)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


## 6. **Random Sampling:**

### 6.1 `numpy.random.choice`
- Generates a random sample from a given 1-D array or sequence.




In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
random_sample = np.random.choice(arr, size=3, replace=False)
print(random_sample)

[5 4 1]
